import datetime
import logging
import os
from pathlib import Path

import boto3


def strtobool(val: str) -> bool:
    """Convert a string representation of truth to True or False."""
    val = val.lower()
    if val in ("y", "yes", "t", "true", "on", "1"):
        return True
    if val in ("n", "no", "f", "false", "off", "0"):
        return False
    raise ValueError(f"Invalid truth value: {val!r}")


logger = logging.getLogger(__name__)

LOG_LEVEL = os.getenv("LOG_LEVEL", "DEBUG")
if LOG_LEVEL and LOG_LEVEL in ("INFO", "ERROR", "WARNING", "DEBUG", "CRITICAL"):
    level = getattr(logging, LOG_LEVEL)
    logger.setLevel(level)

DEFAULT_ENABLE_BOTO3_LOGGING = "False"
ENABLE_BOTO3_LOGGING = bool(strtobool(os.getenv("ENABLE_BOTO3_LOGGING", DEFAULT_ENABLE_BOTO3_LOGGING)))

DEFAULT_API_TITLE = "SANDJIG API"
API_TITLE = os.getenv("API_TITLE", DEFAULT_API_TITLE)
logger.info(f"API_TITLE={API_TITLE}")

DEFAULT_API_VERSION = "v1.0"
API_VERSION = os.getenv("API_VERSION", DEFAULT_API_VERSION)

JST = datetime.timezone(datetime.timedelta(hours=+9))

TESTING = strtobool(os.getenv("TESTING", "False"))

DEFAULT_BASIC_AUTH_USERNAME = "apibasicauthuser"
BASIC_AUTH_USERNAME = os.getenv("BASIC_AUTH_USERNAME", DEFAULT_BASIC_AUTH_USERNAME)
BASIC_AUTH_PASSWORD = os.getenv("BASIC_AUTH_PASSWORD", None)

TEMPLATE_FILEPATH = Path(__file__).parent / "cloudformation" / "app.sam.yaml"

MAX_FILTER_JOBIDS = 175

# -- paging
DEFAULT_ITEMS_PER_PAGE = "250"
ITEMS_PER_PAGE = int(os.getenv("ITEMS_PER_PAGE", DEFAULT_ITEMS_PER_PAGE))
DEFAULT_MIN_ITEMS_PER_PAGE = "50"
MIN_ITEMS_PER_PAGE = int(os.getenv("MIN_ITEMS_PER_PAGE", DEFAULT_MIN_ITEMS_PER_PAGE))
if ITEMS_PER_PAGE < MIN_ITEMS_PER_PAGE:
    logger.warning(
        f"ITEMS_PER_PAGE({ITEMS_PER_PAGE}) < MIN_ITEMS_PER_PAGE({MIN_ITEMS_PER_PAGE}), "
        f"setting MIN_ITEMS_PER_PAGE to {ITEMS_PER_PAGE}"
    )
    MIN_ITEMS_PER_PAGE = ITEMS_PER_PAGE

DEFAULT_MAX_ITEMS_PER_PAGE = "500"
MAX_ITEMS_PER_PAGE = int(os.getenv("MAX_ITEMS_PER_PAGE", DEFAULT_MAX_ITEMS_PER_PAGE))
if ITEMS_PER_PAGE > MAX_ITEMS_PER_PAGE:
    logger.warning(
        f"ITEMS_PER_PAGE({ITEMS_PER_PAGE}) > MAX_ITEMS_PER_PAGE({MAX_ITEMS_PER_PAGE}), "
        f"setting MAX_ITEMS_PER_PAGE to {ITEMS_PER_PAGE}"
    )
    MAX_ITEMS_PER_PAGE = ITEMS_PER_PAGE

# AWS/BOTO3 Configuration
BOTO3_CONNECT_TIMEOUT = 15
AWS_DEFAULT_REGION = os.getenv("AWS_DEFAULT_REGION", "ap-northeast-1")
AWS_PROFILE = os.getenv("AWS_PROFILE", "default")

DEFAULT_DYNAMODB_SERVICE_ENDPOINT = f"https://dynamodb.{AWS_DEFAULT_REGION}.amazonaws.com"
DEFAULT_S3_SERVICE_ENDPOINT = f"https://s3.{AWS_DEFAULT_REGION}.amazonaws.com"
DEFAULT_SQS_SERVICE_ENDPOINT = f"https://sqs.{AWS_DEFAULT_REGION}.amazonaws.com"
DEFAULT_STS_SERVICE_ENDPOINT = f"https://sts.{AWS_DEFAULT_REGION}.amazonaws.com"
DEFAULT_CFN_SERVICE_ENDPOINT = f"https://cloudformation.{AWS_DEFAULT_REGION}.amazonaws.com"

AWS_SERVICE_ENDPOINTS = {
    "dynamodb": os.getenv("DYNAMODB_SERVICE_ENDPOINT", DEFAULT_DYNAMODB_SERVICE_ENDPOINT),
    "s3": os.getenv("S3_SERVICE_ENDPOINT", DEFAULT_S3_SERVICE_ENDPOINT),
    "sqs": os.getenv("SQS_SERVICE_ENDPOINT", DEFAULT_SQS_SERVICE_ENDPOINT),
    "sts": os.getenv("STS_SERVICE_ENDPOINT", DEFAULT_STS_SERVICE_ENDPOINT),
    "cloudformation": os.getenv("CFN_SERVICE_ENDPOINT", DEFAULT_CFN_SERVICE_ENDPOINT),
}
logger.info(f"AWS_SERVICE_ENDPOINTS: {AWS_SERVICE_ENDPOINTS}")

DEFAULT_AWS_ACCOUNT_ID = None
AWS_ACCOUNT_ID = os.getenv("AWS_ACCOUNT_ID", DEFAULT_AWS_ACCOUNT_ID)
if not AWS_ACCOUNT_ID:
    AWS_ACCOUNT_ID = (
        boto3.client("sts", region_name=AWS_DEFAULT_REGION, endpoint_url=AWS_SERVICE_ENDPOINTS["sts"])
        .get_caller_identity()
        .get("Account")
    )
logger.info(f"AWS_ACCOUNT_ID={AWS_ACCOUNT_ID}")

SANDJIG_SUFFIX = os.getenv("SANDJIG_SUFFIX", None)

DEFAULT_PROECESSINGJOB_TIMEOUT_SECONDS = "21600"
PROCESSINGJOB_TIMEOUT_SECONDS = int(os.getenv("PROCESSINGJOB_TIMEOUT_SECONDS", DEFAULT_PROECESSINGJOB_TIMEOUT_SECONDS))
logger.info(f"PROCESSINGJOB_TIMEOUT_SECONDS={PROCESSINGJOB_TIMEOUT_SECONDS}")

PROCESSINGJOB_STATUS_DEFAULT = "pending"

# DyanmoDb Settings

DEFAULT_CREATE_DYNAMODB_RESOURCES_WAIT_SECONDS = 5
CREATE_DYNAMODB_RESOURCES_WAIT_SECONDS = int(
    os.getenv("CREATE_DYNAMODB_RESOURCES_WAIT_SECONDS", DEFAULT_CREATE_DYNAMODB_RESOURCES_WAIT_SECONDS)
)

# -- requests table
REQUESTS_TABLENAME_ROOT = "-sdjob-requests"
DEFAULT_DYNAMODB_PROCESSINGJOB_REQUESTS_TABLENAME = f"test{REQUESTS_TABLENAME_ROOT}"
DYNAMODB_PROCESSINGJOB_REQUESTS_TABLENAME = os.getenv(
    "DYNAMODB_PROCESSINGJOB_REQUESTS_TABLENAME", DEFAULT_DYNAMODB_PROCESSINGJOB_REQUESTS_TABLENAME
)
logger.info(f"DYNAMODB_PROCESSINGJOB_REQUESTS_TABLENAME={DYNAMODB_PROCESSINGJOB_REQUESTS_TABLENAME}")

DEFAULT_DYNAMODB_PROCESSINGJOB_REQUESTS_READ_CAPACITY_UNITS = "2"
DYNAMODB_PROCESSINGJOB_REQUESTS_READ_CAPACITY_UNITS = int(
    os.getenv(
        "DYNAMODB_PROCESSINGJOB_REQUESTS_READ_CAPACITY_UNITS",
        DEFAULT_DYNAMODB_PROCESSINGJOB_REQUESTS_READ_CAPACITY_UNITS,
    )
)

DEFAULT_DYNAMODB_PROCESSINGJOB_REQUESTS_WRITE_CAPACITY_UNITS = "1"
DYNAMODB_PROCESSINGJOB_REQUESTS_WRITE_CAPACITY_UNITS = int(
    os.getenv(
        "DYNAMODB_PROCESSINGJOB_REQUESTS_WRITE_CAPACITY_UNITS",
        DEFAULT_DYNAMODB_PROCESSINGJOB_REQUESTS_WRITE_CAPACITY_UNITS,
    )
)

# -- settings table
SETTINGS_TABLENAME_ROOT = "-sdjob-settings"
DEFAULT_DYNAMODB_PROCESSINGJOB_SETTINGS_TABLENAME = f"test{SETTINGS_TABLENAME_ROOT}"
DYNAMODB_PROCESSINGJOB_SETTINGS_TABLENAME = os.getenv(
    "DYNAMODB_PROCESSINGJOB_SETTINGS_TABLENAME", DEFAULT_DYNAMODB_PROCESSINGJOB_SETTINGS_TABLENAME
)
logger.info(f"DYNAMODB_PROCESSINGJOB_SETTINGS_TABLENAME={DYNAMODB_PROCESSINGJOB_SETTINGS_TABLENAME}")

DEFAULT_DYNAMODB_PROCESSINGJOB_SETTINGS_READ_CAPACITY_UNITS = "2"
DYNAMODB_PROCESSINGJOB_SETTINGS_READ_CAPACITY_UNITS = int(
    os.getenv(
        "DYNAMODB_PROCESSINGJOB_SETTINGS_READ_CAPACITY_UNITS",
        DEFAULT_DYNAMODB_PROCESSINGJOB_SETTINGS_READ_CAPACITY_UNITS,
    )
)

DEFAULT_DYNAMODB_PROCESSINGJOB_SETTINGS_WRITE_CAPACITY_UNITS = "1"
DYNAMODB_PROCESSINGJOB_SETTINGS_WRITE_CAPACITY_UNITS = int(
    os.getenv(
        "DYNAMODB_PROCESSINGJOB_SETTINGS_WRITE_CAPACITY_UNITS",
        DEFAULT_DYNAMODB_PROCESSINGJOB_SETTINGS_WRITE_CAPACITY_UNITS,
    )
)

# -- index
INDEXNAME_ROOT = "-sdjob-index"
DEFAULT_DYNAMODB_SORTINDEX_INDEXNAME = f"test{INDEXNAME_ROOT}"
DYNAMODB_SORTINDEX_INDEXNAME = os.getenv("DYNAMODB_SORTINDEX_INDEXNAME", DEFAULT_DYNAMODB_SORTINDEX_INDEXNAME)
logger.info(f"DYNAMODB_SORTINDEX_INDEXNAME={DYNAMODB_SORTINDEX_INDEXNAME}")

DEFAULT_SORTINDEX_READ_CAPACITY_UNITS = "2"
SORTINDEX_READ_CAPACITY_UNITS = int(os.getenv("SORTINDEX_READ_CAPACITY_UNITS", DEFAULT_SORTINDEX_READ_CAPACITY_UNITS))

DEFAULT_SORTINDEX_WRITE_CAPACITY_UNITS = "1"
SORTINDEX_WRITE_CAPACITY_UNITS = int(
    os.getenv("SORTINDEX_WRITE_CAPACITY_UNITS", DEFAULT_SORTINDEX_WRITE_CAPACITY_UNITS)
)

# SQS Settings
DEFAULT_PROCESSINGJOB_SQS_QUEUE_NAME = "test-processingjob-queue"
PROCESSINGJOB_SQS_QUEUE_NAME = os.getenv("PROCESSINGJOB_SQS_QUEUE_NAME", DEFAULT_PROCESSINGJOB_SQS_QUEUE_NAME)
logger.info(f"PROCESSINGJOB_SQS_QUEUE_NAME={PROCESSINGJOB_SQS_QUEUE_NAME}")

DEFAULT_PROCESSINGJOB_REQUEST_QUEUE_URL = f"http://localhost:4566/{AWS_ACCOUNT_ID}/{PROCESSINGJOB_SQS_QUEUE_NAME}"
PROCESSINGJOB_REQUEST_QUEUE_URL = os.getenv("PROCESSINGJOB_REQUEST_QUEUE_URL", DEFAULT_PROCESSINGJOB_REQUEST_QUEUE_URL)
logger.info(f"PROCESSINGJOB_REQUEST_QUEUE_URL={PROCESSINGJOB_REQUEST_QUEUE_URL}")

DEFAULT_SQSQUEUE_VISIBILITYTIMEOUT = "900"
SQSQUEUE_VISIBILITYTIMEOUT = int(os.getenv("SQSQUEUE_VISIBILITYTIMEOUT", DEFAULT_SQSQUEUE_VISIBILITYTIMEOUT))

DEFAULT_APP_STAGE = "dev"

# template command Settings
DEFAULT_TEMPLATE_OUTPUT_FILEPATH = "app.sam.yaml"

DEFAULT_OPENAPI_SCHEMA_PATH = "/openapi"
OPENAPI_SCHEMA_PATH = os.getenv("OPENAPI_SCHEMA_PATH", DEFAULT_OPENAPI_SCHEMA_PATH)

SETTINGS_ID: str = f"settings-{SANDJIG_SUFFIX}"

DEFAULT_RECORD_TTL_DAYS = None
RECORD_TTL_DAYS = os.getenv("RECORD_TTL_DAYS", DEFAULT_RECORD_TTL_DAYS)
if RECORD_TTL_DAYS is not None:
    RECORD_TTL_DAYS = int(RECORD_TTL_DAYS)

DEFAULT_JSON_AS_ASCII = "False"
JSON_AS_ASCII = bool(strtobool(os.getenv("JSON_AS_ASCII", DEFAULT_JSON_AS_ASCII)))

NEXT_PAGE_HEADER = "X-Next"
